trigger:
- master

pool:
  vmImage: 'LocalPool'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
  displayName: 'Instalar .NET SDK'

- script: dotnet restore
  displayName: 'Restaurar dependencias'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Compilar soluci√≥n'

- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Ejecutar pruebas'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar artefactos'
