trigger:
- master

#Usar agente
pool:
  name: LocalPool

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**/*.sln'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Configurar .NET SDK 8.0'

- script: dotnet restore $(solution)
  displayName: 'Restaurar dependencias'

- script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'Compilar soluci√≥n'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Ejecutar pruebas'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar artefactos'
